version: '3.1'

services:
 mongo:
  image: mongo
  environment:
   MONGO_INITDB_ROOT_USERNAME: mongo
   MONGO_INITDB_ROOT_PASSWORD: mongopass
  ports:
   - 27017:27017
  volumes:
   - ~/Escritorio/practica-mern/dockerDB/db
 
 mongo-express:
  image: mongo-express
  ports:
   - 8081:8081
  environment:
   ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
   ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass